update workflows

diff --git a/.github/actions/1-addition/1-maps/action.yml b/.github/actions/1-addition/1-maps/action.yml
--- a/.github/actions/1-addition/1-maps/action.yml
+++ b/.github/actions/1-addition/1-maps/action.yml
@@ -102,107 +102,131 @@ runs:
         ACTOR: ${{ github.triggering_actor }}
         OWNER: ${{ github.repository_owner }}
       run: |
-        gh variable set RERUN_RUNNER --body "false"
+        if [[ "$GITHUB_JOB" == "lexering" ]]; then
+          gh variable set RERUN_RUNNER --body "false"
+          if [[ "$RUN_MODE" == "MEC30" ]]; then
+            HEADER="Accept: application/vnd.github+json"
+            RESPONSE=$(gh api -H "${HEADER}" repos/${{ github.repository }}/actions/runners)
+            TOTAL_COUNT=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.total_count')
+            STATUS=$(echo "$RESPONSE" | jq -r --arg NAME "${{ env.RUNNER_TITLE }}" '.runners[] | select(.name == $NAME).status')
 
-        HEADER="Accept: application/vnd.github+json"
-        RESPONSE=$(gh api -H "${HEADER}" repos/${{ github.repository }}/actions/runners)
-        TOTAL_COUNT=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.total_count')
-        STATUS=$(echo "$RESPONSE" | jq -r --arg NAME "${{ env.RUNNER_TITLE }}" '.runners[] | select(.name == $NAME).status')
-
-        if [[ "$TOTAL_COUNT" -eq 0 ]]; then
-          export "RUNNER_COUNT=$TOTAL_COUNT"
-          gh variable set RERUN_RUNNER --body "true"
-        elif [[ "$STATUS" == "offline" ]]; then
-          export "RUNNER_STATUS=$STATUS"
-          gh variable set RERUN_RUNNER --body "true"
-          RUNNER_ID=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.runners.[].id')
-          gh api --method DELETE -H "${HEADER}" /repos/${{ github.repository }}/actions/runners/${RUNNER_ID}
+            if [[ "$TOTAL_COUNT" -eq 0 ]]; then
+              export "RUNNER_COUNT=$TOTAL_COUNT"
+              gh variable set RERUN_RUNNER --body "true"
+            elif [[ "$STATUS" == "offline" || "$REMOVE_RUNNER" == "true" ]]; then
+              export "RUNNER_STATUS=$STATUS"
+              gh variable set RERUN_RUNNER --body "true"
+              RUNNER_ID=$(gh api -H "${HEADER}" /repos/${{ github.repository }}/actions/runners --jq '.runners.[].id')
+              gh api --method DELETE -H "${HEADER}" /repos/${{ github.repository }}/actions/runners/${RUNNER_ID}
+            fi
+          fi
         fi
 
         bash /home/runner/work/_actions/eq19/eq19/v2/.github/entrypoint/init.sh ${{ inputs.action_path }}
         mv -f /home/runner/work/_actions/eq19/eq19/v2/.github/entrypoint/dockerfile/* ${{ inputs.action_path }}/
 
     - name: View context attributes
-      uses: actions/github-script@v7
+      uses: actions/github-script@v8
       with:
         script: console.log(context)
 
-    - uses: actions/setup-python@v5
+    - name: Setup Workspace
+      shell: bash
+      run: |
+        echo "🧹 Free disk"
+        sudo rm -rf /usr/share/dotnet
+        sudo rm -rf /usr/local/lib/android
+        sudo rm -rf /usr/lib/google-cloud-sdk
+        docker system prune -af || true
+        docker builder prune -af || true
+
+        echo "⏫ Setting up 100GB tmpfs"
+        sudo mkdir -p /mnt/extra
+        sudo mount -t tmpfs -o size=100G tmpfs /mnt/extra
+          
+        echo "➡️ Syncing workspace"
+        sudo rsync -a "$GITHUB_WORKSPACE/" /mnt/extra/
+
+        echo "➡️ Switching workspace"
+        echo "GITHUB_WORKSPACE=/mnt/extra" >> $GITHUB_ENV
+        echo "GITHUB_WORKSPACE=/mnt/extra" >> $GITHUB_OUTPUT
+
+        # optional symlink to avoid tool breakage
+        sudo rm -rf "$GITHUB_WORKSPACE"
+        sudo ln -s /mnt/extra "$GITHUB_WORKSPACE"
+
+        echo "📌 Workspace successfully expanded." && df -h
+
+    - uses: actions/setup-python@v6
       with:
-        python-version: 3.12
+        python-version: 3.11
         allow-prereleases: true
 
-    - uses: actions/cache@v4
+    - uses: actions/cache@v5
+      if: runner.os == 'Redis'
       with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-pip
 
     - name: 💎 Set ID Token
+      if:  ${{ env.RERUN_RUNNER == 'false' }}
+      uses: 'google-github-actions/auth@v3'
       id: 'auth'
-      uses: 'google-github-actions/auth@v2'
       with:
         token_format: 'id_token'
         create_credentials_file: false
         credentials_json: ${{ inputs.credentials }}
-        id_token_audience: 'https://us-central1-feedmapping.cloudfunctions.net/function'
+        id_token_audience: 'https://us-central1-marketleader.cloudfunctions.net/function'
 
     - name: Install dependencies
+      if: ${{ env.RERUN_RUNNER == 'false' }}
       shell: bash
       env:
-        ACCESS_API: ${{ inputs.api_key }}
-        ACCESS_KEY: ${{ inputs.api_secret }}
-        ACCESS_TOKEN: ${{ inputs.token }}
-        MESSAGE_API: ${{ inputs.chat_id }}
-        MONITOR_TOKEN: ${{ inputs.bot_token }}
-        WARNING_TOKEN: ${{ inputs.logs_token }}
-        PYPI_TOKEN: ${{ inputs.pypi_token }}        
-        DOCKER_HUB_TOKEN: ${{ inputs.hub_token }}
-        DOCKER_HUB_PASSWORD: ${{ inputs.hub_password }}
-        GCP_CREDENTIALS: ${{ inputs.credentials }}
+        BEARER: ${{ steps.auth.outputs.id_token }}
+        APP_PATH: "user_data/ft_client/test_client/app.py"
+        HYPEROPT_PARAM: "user_data/strategies/hyperopt_params.json"
+        ARTIFACT: "user_data/ft_client/test_client/results/orgs.json"
       run: |
         python -m pip -q install --upgrade pip
-        python -m pip -qqq install tensorflow-cpu
-        #python -m pip -qqq install -r ${{ inputs.action_path }}/dataFile/requirements.txt
 
-        ##Ref: https://iree.dev/guides/ml-frameworks/tensorflow/
-        #pip uninstall -y iree-base-compiler iree-base-runtime iree-compiler iree-tools-tf
-        python -m pip -q install --pre iree-base-compiler iree-base-runtime iree-tools-tf -f https://iree.dev/pip-release-links.html
-        python user_data/ft_client/test_client/app.py orgs.json ${{ env.ID }} ${{ env.PARAM || 'nil' }}
-  
-        ##python -m pip -q install -e ./.github/entrypoint/artifact/python
-        ##iree-compile --iree-llvmcpu-list-targets && iree-run-module --list_drivers
+        # Retry install TensorFlow
+        for i in {1..20}; do
+          python -m pip -qqq install "tensorflow-cpu==2.20.0" && break
+          echo "TensorFlow install failed. retry $i..."
+          sleep 5
+        done
 
-        ##Ref: https://github.com/iree-org/iree-experimental
-        ##python ${{ inputs.action_path }}/pythonCode/testIREE.py
-        
-        #sudo apt-get update > /dev/null
-        #sudo apt-get install llvm-17 llvm-17-dev clang-17 mlir-17-tools > /dev/null
-        #export IREE_LLVM_ENABLE_BACKTRACE=1
-        #export LLVM_SYMBOLIZER_PATH=$(which llvm-symbolizer)
+        # Retry install IREE packages
+        for i in {1..20}; do
+          python -m pip -q install --pre iree-base-compiler iree-base-runtime iree-tools-tf -f https://iree.dev/pip-release-links.html && break
+          ##python ${{ inputs.action_path }}/pythonCode/testIREE.py   
+          echo "IREE install failed. retry $i..."
+          sleep 5
+        done
 
+        # Run your pipeline
         ##Ref: https://github.com/eq19/maps/tree/v3/pythonCode
         ##python ${{ github.workspace }}/.github/entrypoint/artifact/python/gellmann.py
         ##cd ${{ inputs.action_path }}/pythonCode && python npreader.py -h && python map.py -h
-
-        # Get all secrets from source repository
-        secrets=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/actions/secrets" | jq -r '.secrets[].name')
-        for secret in $secrets; do gh secret set $secret --repo ${{ env.TARGET_REPOSITORY }} --body "${!secret}"; done
+        bash user_data/ft_client/test_client/maps.sh $ID $JOBS_ID $APP_PATH ${DIR_PATH:-user_data} ${PARAM_NAME:-nil} $ARTIFACT $HYPEROPT_PARAM 
 
     - name: Login to DockerHub
       uses: docker/login-action@v3
+      if:  ${{ env.RERUN_RUNNER == 'true' }}
       with:
         username: ${{ inputs.hub_username }}
         password: ${{ inputs.hub_token }}
 
     - name: 🚀 Initiate Lexer
       uses: devcontainers/ci@v0.3
+      if:  ${{ env.RERUN_RUNNER == 'true' }}
       with:
         skipContainerUserIdUpdate: true
         imageName: ${{ inputs.image_name }}
         imageTag: target-${{ github.run_number }}
         configFile: ${{ inputs.action_path }}/.devcontainer.json
         push: ${{ env.RERUN_RUNNER == 'true' && 'always' || 'never' }}
-        runCmd: bash user_data/ft_client/test_client/maps.sh            
+        #runCmd: bash user_data/ft_client/test_client/maps.sh            
         env: |
           ID=${{ env.ID }}
           GH_TOKEN=${{ env.GH_TOKEN }}
@@ -215,6 +239,7 @@ runs:
           ARTIFACT=user_data/ft_client/test_client/results/orgs.json
 
     - name: 🗑️ Delete Docker Tags AND Images
+      if:  ${{ env.RERUN_RUNNER == 'true' }}
       id: delete_images
       shell: bash
       env:
@@ -223,11 +248,14 @@ runs:
         HUB_PASSWORD: "${{ inputs.hub_password }}"
         MAX_DELETIONS: 15
       run: |
+        #python -m pip -qqq uninstall -y tensorflow tensorflow-cpu keras keras-preprocessing keras-nightly
         ./.github/entrypoint/remote.sh
+                
 
     - name: ⚧️ Rerun workflow if failed
       if: ${{ failure() }}
       shell: bash
       run: |
-        [[ "$GITHUB_JOB" == "lexering" ]] && gh workflow run "main.yml"
-        exit 1
+        [[ "$GITHUB_JOB" == "lexering" ]] && gh workflow run "main.yml" --repo "$REPO_NAME" \
+          --raw-field "RUN_MODE=$RUN_MODE" --raw-field "REMOVE_RUNNER=$RERUN_RUNNER" \
+          --raw-field "REDUCE_EPOCH=$REDUCE_EPOCH" --raw-field "BYPASS_LEXERING=$BYPASS_LEXERING"
diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -1,9 +1,15 @@
-name: Freqtrade Hyperopt Matrix
+name: Freqtrade Matrix Jobs
+run-name: "Freqtrade Matrix: ${{ inputs.RUN_MODE }} (${{ vars.SCORE }})"
 
 on:
   workflow_dispatch:
     inputs:
-      matrix_json:
+      RUN_MODE:
+        description: 'Custom run name'
+        default: 'Hyperopt'
+        required: false
+        type: string
+      MATRIX_JSON:
         description: "Matrix JSON (as string)"
         required: true
 
@@ -20,23 +26,24 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        params: ${{ fromJson(inputs.matrix_json).params }}
+        FIELDS: ${{ fromJson(inputs.MATRIX_JSON).fields }}
 
     env:
+      SCORE: ${{ vars.SCORE }}
+      RUN_MODE: ${{ inputs.RUN_MODE }}
       GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
       RUNNER_TITLE: "Google-optimized-instance"
       TARGET_REPOSITORY: ${{ vars.TARGET_REPOSITORY }}
 
     steps:
       - name: 📥 Checkout Repo
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: ⚙️ Build Maps
         uses: eq19/maps@v8
         id: build-parser
         env:
           JOBS_ID: 1
-          PARAM: ${{ matrix.params }}
         with:
           token: ${{ secrets.ACCESS_TOKEN }}
           chat_id: ${{ secrets.MESSAGE_API }}
@@ -51,34 +58,57 @@ jobs:
 
       - name: 🪂 Install freqtrade
         shell: bash
+        env:
+          VERSION: "2025.12"
         run: |
-          cd user_data/build_helpers && ./install_ta-lib.sh > /dev/null 2>&1
-          cd ${{ github.workspace }} && python -m venv venv && source venv/bin/activate
-          pip install -qq --no-cache-dir ta "numpy<3.0" "plotly==6.1.2"
-          pip install -qq --no-cache-dir -r user_data/build_helpers/requirements-hyperopt.txt
-          pip install -qq --no-cache-dir --no-build-isolation --upgrade freqtrade
-          cat user_data/config_examples/config_exchange.example.json > user_data/config.json
+          cd user_data/build_helpers
+          ./install_ta-lib.sh > /dev/null 2>&1 && rm -rf *.txt
+
+          # Download requirement files from Freqtrade 2025.10 (corrected)
+          for f in requirements.txt requirements-dev.txt requirements-hyperopt.txt requirements-plot.txt requirements-freqai.txt requirements-freqai-rl.txt; do
+            curl -fsSLO --retry 5 --retry-delay 2 \
+            https://raw.githubusercontent.com/freqtrade/freqtrade/$VERSION/$f || true
+          done          
+
+          pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-plot.txt
+          [[ "$RUN_MODE" != "FreqAI" ]] && pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-hyperopt.txt
+          [[ "$RUN_MODE" == "FreqAI" ]] && pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-freqai-rl.txt
+
+          #pip install -qq --no-cache-dir --no-build-isolation --upgrade freqtrade
+          pip install -qq --no-cache-dir ta "numpy<3.0" "aiodns<3.0" "freqtrade==$VERSION"
 
       - name: ⚙️ Get artifact ID
         id: get-artifact-id
-        uses: actions/github-script@v7
+        uses: actions/github-script@v8
         with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            const matrix = JSON.parse(context.payload.inputs.matrix_json);
+            const matrix = JSON.parse(context.payload.inputs.MATRIX_JSON);
             const artifactName = 'freqtrade-data';
             const runId = matrix.run_id;
 
-            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: runId,
-            });
+            for (let i = 0; i < 20; i++) {
+              try {
+                const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  run_id: runId,
+                });
 
-            const match = artifacts.data.artifacts.find(a => a.name === artifactName);
-            if (!match) {
-              throw new Error(`Artifact '${artifactName}' not found in run ${runId}`);
+                const match = artifacts.data.artifacts.find(a => a.name === artifactName);
+
+                if (match) {
+                  core.setOutput('artifact_id', match.id);
+                  return;
+                }
+
+              } catch (e) {
+                console.log(`Attempt ${i + 1} failed: ${e.message}`);
+                await new Promise(r => setTimeout(r, 2000));
+              }
             }
-            core.setOutput('artifact_id', match.id);
+
+            throw new Error("Artifact lookup failed after retries");
 
       - name: Download artifact zip using curl
         run: |
@@ -92,22 +122,16 @@ jobs:
         run: unzip -o freqtrade-data.zip -d user_data/data/
 
       - name: Show contents
-        run: ls -R user_data/data/
+        run: ls -R user_data/data
 
-      - name: 🧠 Run Hyperopt
+      - name: 🧠 Run Script
+        timeout-minutes: 360
         env:
-          LOSS: ${{ fromJson(inputs.matrix_json).loss }}
-          SPACE: ${{ fromJson(inputs.matrix_json).space }}
-          SCORE: ${{ fromJson(inputs.matrix_json).score }}
+          MATRIX_INPUT: ${{ matrix.FIELDS }}
+          ID: ${{ fromJson(inputs.MATRIX_JSON).repo_id }}
+          REDUCE_EPOCH: ${{ fromJson(inputs.MATRIX_JSON).reduce_epoch }}
         run: |
-          echo "Running hyperopt..."
-          echo "Loss: $LOSS"
-          echo "Space: $SPACE"
           echo "Score: $SCORE"
-          bash user_data/ft_client/test_client/feed.sh
-
-          # echo -e "\n$hr\nID: $id 👉 Running $hyperopt_loss\nSpaces: $spaces | Days: $days | Epochs: $epochs\n$hr"
-          # freqtrade hyperopt --timerange ${start_date}-${end_date} --epochs ${epochs} -j 4 \
-          #   --spaces ${spaces} --ignore-missing-spaces --hyperopt-loss ${hyperopt_loss} \
-          #   --enable-protections --analyze-per-epoch  --random-state ${id} \
-          #   --fee=$FEE --logfile /dev/null > /dev/null 2>&1
+          echo "Running $RUN_MODE..."
+          echo "Reduce epoch: $REDUCE_EPOCH"
+          bash user_data/ft_client/test_client/feed.sh $RUN_MODE
